# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropagandistSlogans',
        ),
    ]
