# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_propagandistslogans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
