# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171119_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tips',
            field=models.CharField(default=django.utils.timezone.now, max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
